### ISSUE TITLE
Unit tests for new stats functions

### ISSUE THREAD

**Issue by vientang** [vientang/meetup-softball#10]
We've added new stats functions and will need to write unit tests for them

**Comment by mikebasta** [comment]
1. Create tests in /Users/Mike/documents/meetup-softball/src/utils/__tests__/statsCalc.test.js
use test suite "Update Player Stats", and add different possibilities to check for failure. Test different values (null, undefined, strings, etc) on all advanced stats functions (some are not created yet)

2. Validate logic in statsCalc.js stats calculation functions (start line 274) - use test to add logic to prevent unexpected values

**Comment by mikebasta** [comment]
Tests have been created and used to verify formulas. Functions have protection from dividing by 0.
