### ISSUE TITLE
LeaderBoard page

### ISSUE THREAD

**Issue by vientang** [vientang/meetup-softball#46]

**Comment by vientang** [comment]
- Get player data, sort then filter the top 5
- Consider ties
- Add tooltip to explain qualifiers for rate stats
- Add social share button (for 1st place or maybe for all leaders)

**Comment by mikebasta** [comment]
For Runs Created, sort before truncating decimal value. We only want to display a whole number for the result, but decimals should be accounted for in a tiebreaker situation.
