### ISSUE TITLE
Save meta data to PlayerStats and GameStats

### ISSUE THREAD

**Issue by vientang** [vientang/meetup-softball#69]
Contains information about last game recorded and anything else that could be helpful

Explore the meetup api to find anything interesting.

**Comment by vientang** [comment]
@mikebasta, what were the fields that we've decided to add? Can you list them here? I'll update the api when we find a solution https://github.com/aws-amplify/amplify-cli/issues/850

**Comment by mikebasta** [comment]
**Players**
joined

photo {thumbnail_link, photo_link, highres_link}

group_profile.role

answers[]

group_profile.link

**Games**
latitude

longitude

waitlist_count

yes_rsvp_count

**Comment by vientang** [comment]
We'll need to hit a different endpoint to get these three fields.

- joined
- group_profile.role
- answers[]
