### ISSUE TITLE
Write definitions to explain stat categories and qualifiers

### ISSUE THREAD

**Issue by vientang** [vientang/meetup-softball#82]
1. Make a `constants.js` file. This will hold static data.
2. Create an object called `definitions`, holding key/value pairs that explain the uncommon stat categories (ops, rc, woba, obp, slug).

For example:
```
{ 
  rc: 'Total runs created.......' ,
  woba: 'Weighted on base average.......' 
}
```

3. Create an object called `qualifiers`, holding key/value pairs that explain the minimum qualifying stat for the LeaderBoard cards.
4. Export both objects to be consumable throughout the application.

**Comment by mikebasta** [comment]
Definitions created with both basic (shown on page) and detailed (for coverable tooltip) explanation of stats. "Game minimum" string used for qualifiers, logic for determining minimum amount of qualifying games will need to be handled on LeaderBoard component.
