### ISSUE TITLE
Cannot get authenticated through the site

### ISSUE THREAD

**Issue by vientang** [vientang/meetup-softball#9]
When another developer pulls down the project code, they are unable to log into the site. 

Steps to reproduce:

1. Pull down the latest code from Github. This contains the front end and back end code.
2. Install dependencies.
3. Go to admin page to sign in. 

Issue:
Unable to sign in

**Comment by vientang** [comment]
@mikebasta Can you share what error you're getting?

**Comment by vientang** [comment]
https://github.com/aws-amplify/amplify-cli/issues/211

**Comment by vientang** [comment]
#20

**Comment by vientang** [comment]
I've updated the AWS infrastructure so logging in should be stable now. @mikebasta, let's test this on your machine to verify before closing this ticket.

**Comment by mikebasta** [comment]
Verified.
